### ISSUE TITLE
[Feature] Revise documentation for vars `jira_field_grain` and `issue_field_history_columns`

### ISSUE THREAD

**Issue by dyt783** [fivetran/dbt_jira#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Regardless whether I set `jira_field_grain` as 'field_id' or 'field_name', I don't seem to be able to use the value 'customfield_10028' to define the field in `issue_field_history_columns`. I can use the value 'Story Points' and it works fine with both grain settings.

### Expected behavior

I expect to be able to use the value 'customfield_10028' to define the fields in `issue_field_history_columns`

### dbt Project configurations

# Variables for the Fivetran JIRA package
    jira_database: dw
    jira_schema: jira
    issue_field_history_columns: ['Story Points', 'customfield_10028']
    jira_field_grain: 'field_id' # field_id or field_name

### Package versions

packages:
  - package: dbt-labs/codegen
    version: 0.12.1
  - package: fivetran/ad_reporting
    version: 1.7.0
  - package: fullstorydev/dbt_fullstory
    version: 0.5.1
  - package: fivetran/jira
    version: 0.15.0

### What database are you using dbt with?

snowflake

### dbt Version

1.7

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-catfritz** [comment]
Hi @dyt783, thanks for bringing this up. The `issue_field_history_columns` variable is designed to use the `field_name` only. If you use the corresponding `field_name` for `field_id`=customfield_10028 found in your `field` staging table, that should allow it to pull the custom field through. 

As for the `jira_field_grain` variable, it serves a different purpose. It is for switching the field that our joins and window functions use. It is useful in the case where you might have customfield_01 and customfield_02, but both are named "sprint", and you want them to treated together instead of seprately. 

I hope that helps clear things up, but please let me know if you have any other questions!

**Comment by fivetran-catfritz** [comment]
Updating this issue to a feature to revise documentation since this is not truly a bug. @dyt783 If you have any further comments/questions, you can continue to comment in this thread!
