### ISSUE TITLE
[Bug] Sprint column not correctly mapped

### ISSUE THREAD

**Issue by troyschuetrumpf-elation** [fivetran/dbt_jira#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The Sprint field is not pulled through in `int_jira__daily_field_history`

If you refer to the following commit comment you will see the bug introduction
https://github.com/fivetran/dbt_jira/commit/a1d5865c76d09d390e2361e259fe461f6fd44698#r76693371

### Expected behavior

Sprint history should be pulled through 

### dbt Project configurations

default is fine in this case

### Package versions

0.8.1

### What database are you using dbt with?

redshift

### dbt Version

1.0.8

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
@troyschuetrumpf-elation thanks so much for calling out this bug. There definitely was an adjustment to this code during a previous upgrade that needs to be fixed.

I also agree the code snippet you have pointed out is where we will want to make the adjustment. My understanding is that we will want to change line 32 to reference `sprint` instead of `status`.
https://github.com/fivetran/dbt_jira/blob/b383b19120efadff88abf00ed522fd5527976d93/models/intermediate/field_history/int_jira__daily_field_history.sql#L32

We should also bring that comment into the correct location as well.

I see you marked that you would be open to creating the PR! Let me know if this is something you are still interested in and I would be happy to help with any questions you may have regarding the contribution 😄

**Comment by troyschuetrumpf-elation** [comment]
Hey @fivetran-joemarkiewicz, 
No worries at all 👍 I was adding these models to our internal data warehouse processing, I have to say i'm really happy these exist in the first place! 

More than happy to create a PR (I have the change locally), I think i might need permission to publish the branch to fivetran/dbt_jira though unless there is a different process? 

Agree on also updating the comment, makes sense.

**Comment by troyschuetrumpf-elation** [comment]
Ah never mind i see the documentation in the readme.md, ill create the PR tonight

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for opening this issue and addressing the resolution within your PR 😄!

I just cut the `v0.8.2` release of the dbt_jira package with your changes included. These should be reflected on the dbt hub at the top of the hour. I will close this ticket as the issue has been addressed.
